localizedSettings:
  developerEmail: yarl.van.onckelen@gmail.com
  developerName: It's y@rl
  displayName: Bloempot
  fullDescription: De bloempot die je leven makkelijker maakt. En je plant persoonlijker.
  privacyPolicyUrl: https://itsyarl.be
  pronunciation: Bloempot
  sampleInvocations:
  - Praat met Bloempot
  shortDescription: De vriendelijke bloempot
  smallLogoImage: https://lh3.googleusercontent.com/KhX5b9BJOqhaUAqSnhPXze7Omwh7WAJqw1PvaujHtjK07W72Oglmm20pXajb2BTzlc30-gordao
  voice: female_1
